pysal/esda

- .gitignore
- .travis.yml
- esda/getisord.py
- esda/smoothing.py
- esda/tests/test_gamma.py
- esda/tests/test_geary.py
- esda/tests/test_join_counts.py
- esda/tests/test_mapclassify.py
- esda/tests/test_moran.py
- esda/tests/test_smoothing.py
- setup.py
1. fix syntax errors in the setup file
2. make imports from `libpysal` refer exactly to the file from which the symbol is imported
3. pull in fixes from upstream #903, which fixes the type instability in the headbanging triples
4. 3 makes tests fail on 3.6, so 3.6 support was made optional. When 3.7 is released (or someone figures out the bug to be filed on this), we will reenable 3.6 support.
> Resolve setup issues, merge pysal/#903, and make 3.6 support opt

- esda/moran.py
- esda/tests/test_moran.py
In order to allow for the option zstandard in `splot.esda` visualisations `esda.moran` Objects need to commonly provide input .x, .y and standardised .zx, .zy attributes.
The following were implemented:
*  esda.moran.Moran: .z attribute is divided by standard deviation
* esda.moran.Moran_BV: has non-standardised .x and .y values (input parameters)
*  esda.moran.Moran_Local_BV: has non-standardised .x and .y values (input parameters)
additionally I wrote a test function `test_z_consistency` to test the consistency of the `.z` value over different `esda.moran` objects
> `.z` attribute divided by standard deviation

- .travis.yml
- esda/gamma.py
- esda/geary.py
- esda/getisord.py
- esda/join_counts.py
- esda/moran.py
- esda/smoothing.py
- esda/tests/test_geary.py
- esda/tests/test_mixture_smoothing.py
- esda/tests/test_moran.py
- esda/tests/test_smoothing.py
Hey,
this adds some documentation fixes for `libpysal`'s API change, in attempts to clean up the api for migrating to `pysal 2.0`, as we outline on `migrating.pysal.org`. 
Note that, the way these test are configured now, the "allow_failures" will pass, and the mandatory tests will fail. This is because I have not yet created a `pypi` release of `libpysal`. But, using this optional github-focused test battery, we can see when there are changes in libpysal that may affect our library. That said, no more changes to *existing* libpysal APIs will occur, and submodule maintainers should probably import directly from the python file in which their function exists.
> Accounting for incoming API changes to `libpysal` and adding testing against `libpysal`'s master branch

- esda/getisord.py
- esda/tests/test_getisord.py
- Use a vector of expectations and standard errors rather than scalars when approximating the local normal distributions based on permutations
- More tests and typo corrections.
> BUG: EG_Sim and seG_sim were incorrectly given as scalars. #53

- esda/getisord.py
- esda/join_counts.py
- esda/moran.py
This PR is to fix the doc building bug https://github.com/pysal/esda/issues/55
It turns out that [some docstrings in `esda` under the `See Also` section](https://github.com/pysal/esda/blob/master/esda/moran.py#L258) do not meet [the requirement as defined in numpydoc](https://numpydoc.readthedocs.io/en/latest/format.html#sections). 
After deleting the sections `See Also` (I do not see them particularly necessary here), the docs build fine.
> (bug) fix docs build

- esda/lee.py
This adds the Lee local spatial pearson estimators, alongside a wrapped version of the R code you can use to get them from spdep. This still needs
> add Lee (2001) local spatial Pearson

- esda/join_counts.py
- esda/tests/test_join_counts.py
In response to https://github.com/pysal/esda/issues/48.
1. Added autocorr_neg and autocorr_pos as instance attributes to Join_Counts class
2. Added relevant tests to the Join_Counts_Tester class
Will create a separate branch on my fork / fork off my fork to update the docs associated with Join_Counts
> ENH - Join count tails

- .travis.yml
- requirements_dev.txt
Addressing #92, regarding
* the exclusion of `pip` released `libpysal` versions from the testing matrix
* streamlining of preamble (python versions, environment variables, etc.)
* minor formatting issues
> addressing #92 -- .travis.yml issue

- notebooks/geosilhouettes.ipynb
Parentheses in the DOI url for Rousseeuw 1987 paper caused the link to render incorrectly on Github preview of notebook and resulted in a dead link. Reformatted link to render properly and direct to the paper.
> DOC: fixing link in geosilhouettes notebook

- README.md
- esda/adbscan.py
- esda/geary.py
- tests/test_geary.py
This makes 
1. geopandas a function-level import 
2.  `adbscan` (formally) a scikit-learn estimator by making its inheritance from `_ClusterMixin` and `BaseEstimator` explicit. 
I don't think this affects anything, but it'd be good to check more than the existing test suite...
> Adbscan fix

- setup.py
Add [the missing comma in setup.py](https://github.com/pysal/esda/blob/master/setup.py#L46). 
[It is causing an error in the installation of the github version](https://github.com/weikang9009/giddy/runs/859877500).
> (BUG) missing comma in setup.py

- .github/workflows/unittests.yml
Update conda recipe to avoid failure due to https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
> CI: update conda setup

- esda/crand.py
There were two issues in the concatenation code for the local statistics
for the parallel conditional permutation code. The original code is
below:
> rlocals = numpy.hstack(rlocals).flatten()
The first big issue is that rlocals is a numpy array containing the
random realizations of simulations for observations within each
processing job. This code, however, will flatten that out into an array
of chunk_size*p_permutations, which certainly is not correct.
The second (slightly smaller) issue is that hstack fails when its chunks
are heterogeneously sized, even when you just want to stack over the
rows. For example:
```
>>> a = numpy.arange(20).reshape(4,5)
>>> b = numpy.arange(10).reshape(2,5)
>>> c = numpy.hstack((a,b)) # Fails!
```
That last numpy.hstack line fails with a ValueError, since …
> fix concatenation for random statistics

- docsrc/_static/references.bib
- esda/moran.py
- esda/tests/test_moran.py
[Sokal (1998)](https://onlinelibrary.wiley.com/doi/pdf/10.1111/j.1538-4632.1998.tb00406.x) provides a pretty solid argument about the differences between analytical moments derived from the "total" randomization null and the "conditional" randomization null for local Moran's I. The original article by @lanselin uses the "total" null, as does [spdep](https://github.com/r-spatial/spdep/blob/master/R/localmoran.R#L61). 
This adds both the "total" and the "conditional" implementations to the `Moran_Local` class, in hopes of shedding a bit more light on the [Bivand and Wong (2018)](https://link.springer.com/article/10.1007/s11749-018-0599-x) results about heteroskedasticity and our conditional permutation method. I also have a numba-fied version of the `w_i(kh)` quantity from the original …
> Moments for Moran's I_i following Sokal 1998

- docs/api.rst
Updated `api.rst` to include all local join count functions and local geary functions (from GSOC 2020). 
Nested `Geary_Local` and `Geary_Local_MV` under Geary Statistics. Nested `Join_Counts_Local_BV` and `Join_Counts_Local_MV` under Join Count Local Statistics. 
In addition, reviewed docstrings for the GSOC2020 functions as I noticed mine are not fully rendering in rtd. Unclear why. For example: [moran.py](https://github.com/pysal/esda/blob/master/esda/moran.py), [moran on rtd](https://pysal.org/esda/generated/esda.Moran.html#esda.Moran); [losh.py](https://github.com/pysal/esda/blob/master/esda/losh.py), [LOSH on rtd](https://pysal.org/esda/generated/esda.LOSH.html#esda.LOSH). Thoughts?
> [DOC] Updating read the docs api for local join counts, local geary

- esda/geary_local_mv.py
Partial fix of #181.
Passed testing with `nosetests`:
```
............................................SS.S...S.S.S.................................SSS............................
----------------------------------------------------------------------
Ran 120 tests in 19.110s
```
> [PERF] List comprehension to array operation in local multivariate Geary

- esda/__init__.py
- esda/map_comparison.py
- esda/shape.py
This moves the pygeos imports into a safe spot in the `_cast` function (and depends on `crand` for the `numba` logic. 
Tests pass in a `pygeos`-less environment, but you can't use the map comparison or shape statistics measures. 
I think if we add more modules with `pygeos` functionality, we need to make it a dependency in the next 6-month cycle.
> add pygeos-tolerant fails for the module

- esda/geary_local.py
- esda/geary_local_mv.py
Addressing: https://github.com/pysal/esda/issues/192
Explanation of issue: As noted by @Michel-Anton, the current use of `.groupby` in local_geary.py and local_geary_MV.py can lead to a loss of order in the weight IDs, specifically when the weight IDs use a custom order. The consequence of this loss of order is that the resulting G and p-values will be out of order, creating possibilities for mapping or interpreting values incorrectly. 
Explanation of fix: as suggested by Michel-Anton and @ljwolf in the issue ticket, the order of the temporary object where values are stored should be rearranged according to the values of the weight IDs. No dynamic code should be needed as weights operating on 0-n will be unchanged when reordered, and 
To fix the issue I have added a couple small lines. …
> Preserving w order in local Geary values

- .coveragerc
This PR adds a `.coveragerc` configuration to not check certain files for coverage.
> add .coveragerc

- .github/workflows/testing.yml
- ci/310-DEV.yaml
- ci/310-numba-DEV.yaml
- ci/310.yaml
- ci/311-DEV.yaml
- ci/311-numba-DEV.yaml
- ci/311-numba.yaml
- ci/311.yaml
- ci/38-numba.yaml
- ci/38.yaml
- ci/39-numba.yaml
- ci/39.yaml
- esda/geary.py
- esda/getisord.py
- esda/lee.py
- esda/moran.py
- esda/tests/test_lee.py
This addresses a few bugs filed on the Lee statistic, as well as addressing the precision concerns raised in #243 with using `1-stats.norm.cdf()`.
> Bug fixes across Lee and swap to survival function for #243

- esda/shape.py
- esda/tests/test_shape.py
We now compute an area of a minimum bounding circle from its polygonal representation, which is not as precise as it could be. I am replacing it with `shapely.minimum_bounding_radius` and classic pi times the radius squared formula to avoid that.
The actual numerical difference is negligible in any useful case but there's no reason to not be more precise. And it will likely be faster this way.
> Use more precise calculation of minimum bounding circle area

- .gitignore
- esda/shape.py
- esda/tests/test_shape.py
This addresses #260 by: 
1. ensuring the center of mass calculations refer to the centroid, rather than taking raw coordinates. This was done correctly in the `moment_of_inertia()` function, but not the `second_areal_moment()` function, which is needed for some of the other compactness measures. 
2. calculate the sum of moments, rather than the product, for the computation. This is not specified by Li, but is implicit in the representation of the trapezoidal decomposition from Li et al. (2013). Checking that against the [general shoelace-theorem decomposition](https://en.wikipedia.org/wiki/Second_moment_of_area#Any_polygon), we find that the correct formulation to match Li is `I_x + I_y`, not `I_{xy}`. 
3. propagate contributions from multipolygon parts and holes using the parallel axis …
> fix second areal moment calculation, cascade changes down to other stats

- .github/workflows/testing.yml
- esda/getisord.py
- esda/smoothing.py
* This PR resolves #271.
* xref https://github.com/pysal/libpysal/issues/605
> Adjust imports to updates in `libpysal`

- esda/tests/test_crand.py
This adds coverage for `crand.vec_permtuations`.
It was inspired by attempting to change our random number generation scheme to follow the [modern tooling in numpy](https://numpy.org/doc/stable/reference/random/generator.html).
However, `numpy.random.Generator.choice` [is not yet supported in numba](https://github.com/numba/numba/issues/8519).
So, that update will have to wait until a new version of numba that supports the new Generator.
For now, this PR  adds some test coverage for our existing implementation.
> Adding coverage for vec_permutations

- esda/losh.py
- esda/silhouettes.py
- esda/tests/test_losh.py
- esda/tests/test_silhouette.py
This should be the last of the PRs ensuring that esda os Graph-ready.
Once they're all merged I'll do some minor cleanup to avoid unnecessary code duplication.
> ENH: natively support Graph in losh and sihouettes modules

- esda/shape.py
> remove `xtyt` & `xhyh` in `shape._second_moa_ring_xplusy()`

- esda/tests/test_getisord.py
> xfail for `test_G_star_Row_Standardized`

- esda/tests/test_topo.py
- esda/tests/test_util.py
This PR:
* formats, lints, and migrates to `pytest`
* `tests/test_utils.py` 
* `tests/test_topo.py` 
------------
xref:
* #323 
* #335
>  formats, lints, pytest pt. 1 -- `test_{utils,topo}.py`

- esda/tests/test_adbscan.py
This PR:
* formats, lints, and migrates to `pytest`
* `test_adbscan.py ` 
------------
xref:
* #323 
* #335
>  formats, lints, pytest pt. 2 -- `test_adbscan.py `

- README.md
- ci/312-min.yaml
- esda/moran.py
- pyproject.toml
Right now matplotlib is an implicit dependency of the library. By moving the import statement inside the function that uses it, esda will no longer break consumers that dont take a dependency on matplotlib explicitly.
> make matplotlib optional

- esda/moran.py
Add a space so the Sphinx generated documentation formats properly.
https://pysal.org/esda/generated/esda.Moran.html#esda.Moran
> Fix typo in documentation.

- esda/moran.py
- esda/tests/test_moran.py
This adds a method to plot a scatterplot from Moran_Local and Moran based on the splot implementation with some changes. 
1. It is more restricted - always use standardised values, always enforce equal aspect
2. Limited figure customisation - splot has opinionated style of axes. Leaving this to a user here.
3. Rely on scipy to do the regression to avoid additional dependency on spreg.
As a follow up, I want to figure out a smart way of colour customisation but didn't give it much thought yet.
Regarding the API, should we go with `plot_scatterplot` or just simply `scatterplot`?
> ENH: add Moran scatterplot ported from splot

- ci/310-numba-oldest.yaml
- ci/310-oldest.yaml
- ci/311-latest.yaml
- ci/311-numba-latest.yaml
- ci/312-dev.yaml
- ci/312-latest.yaml
- ci/312-numba-dev.yaml
- ci/312-numba-latest.yaml
- esda/moran.py
- esda/tests/test_moran.py
- pyproject.toml
Another port from splot, this time `plot_simulation`. Dropping `aspect_equal` keyword as it does not make sense here given the two axes are using distinct units. 
I have also added labels to vertical lines indicating I and EI, so that they show up in legend if you do `plt.legend()`.
> ENH: add Moran.plot_simulation and Moran_BV.plot_simulation

- esda/moran.py
This exposes scatterplot plotting on BV versions of Moran as well, using the same implementation. Together with #357 this concludes move of the individual plotting functions from `splot`. Remaining stuff is are just subplots which I am not sure is wort moving.
> ENH: expose scatterplot on bivariate Moran stats

- esda/moran.py
Setting transformation to "U" causes an "unsupported weights transformation" exception because "U" is not an accepted parameter of the set_transform method of the libpysal.weights.W class. The correct argument is "O", which is described in the [libpysal.weights.W documentation](https://pysal.org/libpysal/generated/libpysal.weights.W.html#libpysal.weights.W.set_transform) as "Restore original transformation (from instantiation)". I've updated the documentation to reflect that.
> Correct documentation

- esda/moran.py
- esda/tests/test_moran.py
This is the final PR with remaining splot stuff. As I went, I realised that some of the earlier basic plotting functionality is not exposed on `Moran_Local_BV` so I did it as well (I needed that anyway here).
I have renamed `plot_local_autocorrelation` from esda to `plot_combination` as the former feels strange as a method name but I am open to any naming suggestions.
> ENH: add plot_combination to Moran_Local and Moran_Local_BV and basic plotting to Moran_Local_BV

- docs/api.rst
- esda/__init__.py
- esda/moran.py
- esda/tests/test_moran.py
This is nearly 1:1, I just replaced the scatterplot functions for those we already have here and properly specified which spines should be shown and which not. The resulting plot is the exact version of the one `splot` does.
Tests do not repeat what is tested in scatter itself, so focusing only on the subplot grid and its specification.
> ENH: move moran_facet plotting from splot
