pysal/esda

- esda/gamma.py
- esda/geary.py
- esda/getisord.py
- esda/join_counts.py
- esda/mixture_smoothing.py
- esda/moran.py
- esda/smoothing.py
- esda/tests/test_smoothing.py
All doctests pass now, except two for Headbanging that now (correctly) raises a Deprecation warning. This addresses #4
> Update docstrings to use libpysal not pysal

- .gitignore
- setup.py
> include /tests in release

- README.md
- esda/__init__.py
- esda/smoothing.py
- esda/tests/test_getisord.py
- esda/tests/test_smoothing.py
- setup.py
> Changing esda setup to handle version programatically

- esda/geary.py
Incorporates downstream [fix](https://github.com/pysal/pysal/pull/1040).
> DOC: correcting Geary documentation

- MANIFEST.in
- setup.py
Fixes https://github.com/pysal/esda/issues/65
> Use README.rst instead of README.md in setup.py b/c the former is in the sdist

- esda/moran.py
> correcting typo from (#60)

- doc/_static/references.bib
- doc/api.rst
- esda/__init__.py
- esda/lee.py
- requirements.txt
Will do a new release as this also has a fix for #65.
> REL: update setup and add Lee statistics

- esda/gamma.py
- esda/tests/test_gamma.py
This changes the `yes` to a `True` option for standardize in `gamma.py`
> deprecate standardize option

- doc/_static/references.bib
- esda/__init__.py
- esda/silhouettes.py
- esda/tests/test_silhouette.py
- requirements_tests.txt
This is a clean version of #50
> [ENH]: Geosilhouettes

- doc/installation.rst
- setup.py
> officially supported Python versions

- README.md
- README.rst
> resolving dev guidelines link

- esda/geary.py
- tests/test_geary.py
- Addresses #44 
- Uses Columbus to test
> ENH: More efficient Geary implementation with new test data

- .dependabot.yml
This PR following #128 to check for dependency/requirement updates through GHA.
> adding dependabot

- .github/workflows/unittests.yml
- ci/36.yaml
- ci/37.yaml
- ci/38.yaml
- setup.py
[Ref](https://gitter.im/pysal/pysal?at=5fb63374bf955735eb8b8c68).
> Dropping 3.6 from testing.

- .github/workflows/upload_package.yml
- esda/__init__.py
- tools/gitcount.ipynb
- We missed tagging the last release so I added a manual start date
- After this is merged, we can tag and cut a release
> Prepping for 2.3.2 release.

- README.md
This is a start at addressing #142, which we encountered during #116
> document minimum numba version

- esda/__init__.py
This moves the version to 2.3.6 to incorporate additional changes in Jan 2021
> bump version for release

- notebooks/Spatial Autocorrelation for Areal Unit Data.ipynb
Minor text changes: fix reference to list prices and a cell result value.
> Update Spatial Autocorrelation for Areal Unit Data

- .github/workflows/unittests.yml
update codecov action to v2 (from jGaboardi/esda)
> update codecov action to v2

- docs/api.rst
- esda/adbscan.py
- esda/crand.py
- esda/geary.py
- esda/geary_local.py
- esda/geary_local_mv.py
- esda/join_counts.py
- esda/join_counts_local.py
- esda/join_counts_local_bv.py
- esda/join_counts_local_mv.py
- esda/lee.py
- esda/losh.py
- esda/map_comparison.py
- esda/moran.py
- esda/shape.py
- esda/silhouettes.py
- esda/tabular.py
- esda/topo.py
- esda/util.py
We are using wrong section names in some doctsrings and they are then ignored by sphinx, hence missing from the docs. This PR is mostly changing ignored `Arguments` to proper `Parameters`.
Some files were blacken along the way, that is why the diff is larger but I haven't touched any code.
> DOC: ensure docstrings are rendering

- esda/topo.py
> Remove matplotlib import

- .github/workflows/unittests.yml
> only download datasets needed for CI testing

- codecov.yml
This PR customizes the `codecov` reporting badge.
> custom codecov reporting

- esda/adbscan.py
- esda/tests/test_adbscan.py
> ensure `min_sample>=1`  in `adbscan`

- esda/geary_local_mv.py
> BUG: Don't include w.id_order in calculation of local C

- docs/index.rst
> Update link to notebooks on landing page

- docs/_static/references.bib
> DOC: fix adbscan reference

- .gitignore
- esda/shape.py
* This PR resolves #300.
* Example fix in [CI (ubuntu-latest, ci/311-numba-DEV.yaml)](https://github.com/pysal/esda/actions/runs/9861748202/job/27230862615?pr=306)
* ***Other failures unrelated to this PR.***
> `numpy.math.atan2` -> `numpy.atan2` in `shape._get_angles()`

- README.md
- docs/index.rst
This PR:
* resolves #324 
* xref https://github.com/pysal/pysal/issues/1296
> update chat link -- gitter >> discord

- ci/310-numba-oldest.yaml
- ci/310-oldest.yaml
- ci/311-latest.yaml
- ci/311-numba-latest.yaml
- ci/312-latest.yaml
- ci/312-min.yaml
- ci/312-numba-latest.yaml
- environment.yml
- pyproject.toml
This should make all of the Graph PRs green.
> pin libpysal to 4.12

- README.md
This PR:
* resolves #319
* xref https://github.com/pysal/esda/pull/296#issuecomment-2231798831
> min pin for `libpysal` in README - resolve #319

- ci/310-oldest.yaml
- esda/gamma.py
- esda/getisord.py
- esda/tests/test_gamma.py
- esda/tests/test_getisord.py
I have vectorized Gamma computation which is now about 10x faster on a dummy lat2W(40, 40) graph.
> ENH: natively support Graph in getisord and gamma modules

- .pre-commit-config.yaml
- esda/adbscan.py
- esda/crand.py
- esda/gamma.py
- esda/geary.py
- esda/geary_local.py
- esda/geary_local_mv.py
- esda/getisord.py
- esda/join_counts.py
- esda/join_counts_local.py
- esda/join_counts_local_bv.py
- esda/join_counts_local_mv.py
- esda/lee.py
- esda/losh.py
- esda/map_comparison.py
- esda/mixture_smoothing.py
- esda/moran.py
- esda/shape.py
- esda/silhouettes.py
- esda/smaup.py
- esda/smoothing.py
- esda/tabular.py
- esda/topo.py
- pyproject.toml
This PR:
* resolves #308 
* resolves #330 
* removes the old Python 3.8 pin for linting --> relints to Python 3.10 standards
* failures due to #331 
* not related to this PR
* being solved in #336
> drop `black` - reup linting w/0 Python 3.8 pin

- esda/moran.py
> small factor of `moran.Moran_Local_BV.__calc()`

- esda/moran.py
- esda/tests/test_moran.py
This re-uses the tooling for `explore` and exposes the static version of the map using `GeoDataFrame.plot`.
> ENH: add Moran_Local.plot

- esda/tests/test_geary.py
> Set seed before permutations for reproducibility

- .github/workflows/build_docs.yml
As found by @martinfleis the block removed in this PR is no longer needed, if it was previously.
> remove random block in `build_docs` action
